### ISSUE TITLE
Error processing large image

### ISSUE THREAD

**Issue by JayVDZ** [huyaoyu/ImageFlow#4]
I've got a C# worker using ImageFlow (love it) that processes uploaded images (resize down to webp). It's normally okay handling large images (we accept up to 100MB), but it's barfing on one with the following error:

```
(InternalError: Failed to allocate 14204x10652x4 bitmap (605204032 bytes). Reduce dimensions or increase RAM.: CError 52: Invalid dimensions
bitmap_formats.c:104: in function flow_bitmap_bgra_create_header
bitmap_formats.c:129: in function flow_bitmap_bgra_create
 at
imageflow_core/src/ffi.rs:293:28
https://github.com/imazen/imageflow/blob/16873d7816046754c75dc6a0b968f600f7caf6fe/imageflow_core/src/ffi.rs#L293
imageflow_core/src/flow/nodes/codecs_and_pointer.rs:208:65
https://github.com/imazen/imageflow/blob/16873d7816046754c75dc6a0b968f600f7caf6fe/imageflow_core/src/flow/nodes/codecs_and_pointer.rs#L208
imageflow_core/src/flow/execution_engine.rs:488:114
https://github.com/imazen/imageflow/blob/16873d7816046754c75dc6a0b968f600f7caf6fe/imageflow_core/src/flow/execution_engine.rs#L488
imageflow_core/src/context.rs:284:59
https://github.com/imazen/imageflow/blob/16873d7816046754c75dc6a0b968f600f7caf6fe/imageflow_core/src/context.rs#L284
imageflow_core/src/context_methods.rs:50:68
https://github.com/imazen/imageflow/blob/16873d7816046754c75dc6a0b968f600f7caf6fe/imageflow_core/src/context_methods.rs#L50
Active node:
NodeDebugInfo {
    stable_id: 1,
    params: Json(
        Decode {
            io_id: 0,
            commands: None,
        },
    ),
    index: NodeIndex(1),
}

)

   at Imageflow.Bindings.JobContext.AssertReady()
   at Imageflow.Bindings.JobContext.SendJsonBytes(String method, Byte[] utf8Json)
   at Imageflow.Bindings.JobContext.Execute[T](T message)
   at Imageflow.Fluent.ImageJob.FinishAsync(JobExecutionOptions executionOptions, SecurityOptions securityOptions, CancellationToken cancellationToken)
```

Ram doesn't appear to be an issue, it's a 32GB server, using about 6GB and there's no spikes when the image is processed. 
SetSecurityOptions() has been set to allow such images.

Is this something I can configure my way out of, or is it an internal limitation?

Here's the image file: https://tetron-my.sharepoint.com/:i:/g/personal/jay_tetron_io/ETtP5Hl0vbdNgD2Zs6rkyGkBn0l4GcODi_-wwwJCmbzV4g?e=XF9nbZ

**Comment by huyaoyu** [comment]
It seems you're using another repo other than this one.
